# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo/find5/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/oppo/find5/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \
	vendor/oppo/find5/proprietary/lib/libmmjpeg.so:obj/lib/libmmjpeg.so

PRODUCT_COPY_FILES += \
  vendor/oppo/find5/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
  vendor/oppo/find5/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
  vendor/oppo/find5/proprietary/bin/btnvtool:system/bin/btnvtool \
  vendor/oppo/find5/proprietary/bin/cnd:system/bin/cnd \
  vendor/oppo/find5/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
  vendor/oppo/find5/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
  vendor/oppo/find5/proprietary/bin/efsks:system/bin/efsks \
  vendor/oppo/find5/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
  vendor/oppo/find5/proprietary/bin/ks:system/bin/ks \
  vendor/oppo/find5/proprietary/bin/mpdecision:system/bin/mpdecision \
  vendor/oppo/find5/proprietary/bin/netmgrd:system/bin/netmgrd \
  vendor/oppo/find5/proprietary/bin/nv_tee:system/bin/nv_tee \
  vendor/oppo/find5/proprietary/bin/nl_listener:system/bin/nl_listener \
  vendor/oppo/find5/proprietary/bin/port-bridge:system/bin/port-bridge \
  vendor/oppo/find5/proprietary/bin/qcks:system/bin/qcks \
  vendor/oppo/find5/proprietary/bin/qmiproxy:system/bin/qmiproxy \
  vendor/oppo/find5/proprietary/bin/qmuxd:system/bin/qmuxd \
  vendor/oppo/find5/proprietary/bin/qosmgr:system/bin/qosmgr \
  vendor/oppo/find5/proprietary/bin/qseecomd:system/bin/qseecomd \
  vendor/oppo/find5/proprietary/bin/radish:system/bin/radish \
  vendor/oppo/find5/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/oppo/find5/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
  vendor/oppo/find5/proprietary/bin/time_daemon:system/bin/time_daemon \
  vendor/oppo/find5/proprietary/bin/thermald:system/bin/thermald \
  vendor/oppo/find5/proprietary/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
  vendor/oppo/find5/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
  vendor/oppo/find5/proprietary/lib/libalsautils.so:system/lib/libalsautils.so \
  vendor/oppo/find5/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
  vendor/oppo/find5/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
  vendor/oppo/find5/proprietary/lib/libaudioparsers.so:system/lib/libaudioparsers.so \
  vendor/oppo/find5/proprietary/lib/libc2d2_a3xx.so:system/lib/libc2d2_a3xx.so \
  vendor/oppo/find5/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
  vendor/oppo/find5/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
  vendor/oppo/find5/proprietary/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
  vendor/oppo/find5/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
  vendor/oppo/find5/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
  vendor/oppo/find5/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
  vendor/oppo/find5/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
  vendor/oppo/find5/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
  vendor/oppo/find5/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
  vendor/oppo/find5/proprietary/lib/egl/libplayback_adreno200.so:system/lib/egl/libplayback_adreno200.so \
  vendor/oppo/find5/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
  vendor/oppo/find5/proprietary/lib/libgsl.so:system/lib/libgsl.so \
  vendor/oppo/find5/proprietary/lib/libllvm-a3xx.so:system/lib/libllvm-a3xx.so \
  vendor/oppo/find5/proprietary/lib/libOpenCL.so:system/lib/libOpenCL.so \
  vendor/oppo/find5/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
  vendor/oppo/find5/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
  vendor/oppo/find5/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/oppo/find5/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/oppo/find5/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/oppo/find5/proprietary/lib/libmmjps.so:system/lib/libmmjps.so \
  vendor/oppo/find5/proprietary/lib/libmmmpo.so:system/lib/libmmmpo.so \
  vendor/oppo/find5/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
  vendor/oppo/find5/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
  vendor/oppo/find5/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
  vendor/oppo/find5/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
  vendor/oppo/find5/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
  vendor/oppo/find5/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
  vendor/oppo/find5/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
  vendor/oppo/find5/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
  vendor/oppo/find5/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
  vendor/oppo/find5/proprietary/lib/hw/nfc.default.so:system/lib/hw/nfc.default.so \
  vendor/oppo/find5/proprietary/lib/libdiag.so:system/lib/libdiag.so \
  vendor/oppo/find5/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
  vendor/oppo/find5/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \
  vendor/oppo/find5/proprietary/lib/libdss.so:system/lib/libdss.so \
  vendor/oppo/find5/proprietary/lib/libdsucsd.so:system/lib/libdsucsd.so \
  vendor/oppo/find5/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/oppo/find5/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/oppo/find5/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
  vendor/oppo/find5/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
  vendor/oppo/find5/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
  vendor/oppo/find5/proprietary/lib/libmac.so:system/lib/libmac.so \
  vendor/oppo/find5/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
  vendor/oppo/find5/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
  vendor/oppo/find5/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
  vendor/oppo/find5/proprietary/lib/libCommandSvc.so:system/lib/libCommandSvc.so \
  vendor/oppo/find5/proprietary/lib/libconfigdb.so:system/lib/libconfigdb.so \
  vendor/oppo/find5/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
  vendor/oppo/find5/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
  vendor/oppo/find5/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
  vendor/oppo/find5/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
  vendor/oppo/find5/proprietary/lib/libqdi.so:system/lib/libqdi.so \
  vendor/oppo/find5/proprietary/lib/libqdp.so:system/lib/libqdp.so \
  vendor/oppo/find5/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/oppo/find5/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
  vendor/oppo/find5/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
  vendor/oppo/find5/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
  vendor/oppo/find5/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
  vendor/oppo/find5/proprietary/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
  vendor/oppo/find5/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
  vendor/oppo/find5/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
  vendor/oppo/find5/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
  vendor/oppo/find5/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
  vendor/oppo/find5/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
  vendor/oppo/find5/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
  vendor/oppo/find5/proprietary/lib/libAKM.so:system/lib/libAKM.so \
  vendor/oppo/find5/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
  vendor/oppo/find5/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
  vendor/oppo/find5/proprietary/lib/libsensor_user_cal.so:system/lib/libsensor_user_cal.so \
  vendor/oppo/find5/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
  vendor/oppo/find5/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
  vendor/oppo/find5/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
  vendor/oppo/find5/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
  vendor/oppo/find5/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
  vendor/oppo/find5/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
  vendor/oppo/find5/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
  vendor/oppo/find5/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
  vendor/oppo/find5/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
  vendor/oppo/find5/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
  vendor/oppo/find5/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
  vendor/oppo/find5/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
  vendor/oppo/find5/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
  vendor/oppo/find5/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
  vendor/oppo/find5/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
  vendor/oppo/find5/proprietary/lib/hw/lights.msm8960.so:system/lib/hw/lights.msm8960.so \
  vendor/oppo/find5/proprietary/lib/hw/raw_part.default.so:system/lib/hw/raw_part.default.so \
  vendor/oppo/find5/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
  vendor/oppo/find5/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
  vendor/oppo/find5/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
  vendor/oppo/find5/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
  vendor/oppo/find5/proprietary/vendor/lib/hw/power.qcom.so:system/vendor/lib/hw/power.qcom.so \
  vendor/oppo/find5/proprietary/lib/lib_dlb_msd.so:system/lib/lib_dlb_msd.so \
  vendor/oppo/find5/proprietary/lib/libxml.so:system/lib/libxml.so \
  vendor/oppo/find5/proprietary/lib/libSHIMDivxDrm.so:system/lib/libSHIMDivxDrm.so
